name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: my_database
          POSTGRES_USER: my_user
          POSTGRES_PASSWORD: my_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U my_user -d my_database -q"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:  
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL_TEST: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./server

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run Database Migrations
        run: |
          npm run migrate
        working-directory: ./server

      - name: Build the project
        run: |
          npm run build
        working-directory: ./server

      - name: Run tests
        run: |
          npm test
        working-directory: ./server
